services:
  - type: web
    name: musicmate-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "7000"
      - key: CLIENT_URL
        value: "https://musicmate-frontend.onrender.com"
      - key: REDIS_URL
        fromService:
          type: redis
          name: musicmate-redis
          property: connectionString
      - key: MONGODB_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: ADMIN_MAIL
        sync: false
      - key: SMTP_SERVICE
        sync: false
      - key: SMTP_MAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: APPROVAL_TOKEN_SECRET
        sync: false

  - type: redis
    name: musicmate-redis
    plan: free
    ipAllowList: [] # Only allow internal connections within Render
